plugins {
    id 'io.qameta.allure' version '4.3.0'
}

group = 'io.student'
version = '1.0.0'

def allureJavaVersion = '3.0.0'
def allureReportVersion = '3.17.0'
def aspectJVersion = '1.9.25.1'
def junitVersion = '6.1.3'
def playwrightVersion = '1.63.0'

configurations {
    agent {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    agent "org.aspectj:aspectjweaver:$aspectJVersion"

    testImplementation platform("org.junit:junit-bom:$junitVersion")
    testImplementation platform("io.qameta.allure:allure-bom:$allureJavaVersion")

    testImplementation "io.qameta.allure:allure-jupiter"
    testImplementation "io.qameta.allure:allure-playwright"
    testImplementation "com.microsoft.playwright:playwright:$playwrightVersion"

    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
    testRuntimeOnly "org.aspectj:aspectjrt:$aspectJVersion"
}


allure {
    version = allureReportVersion
    adapter {
        autoconfigure.set(false)
    }
}

test {
    useJUnitPlatform()
    jvmArgumentProviders.add({ ["-javaagent:${configurations.agent.singleFile}"] } as CommandLineArgumentProvider)
}
